import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-rail-demurrage-accessorial-recovery",
  "engine": "recovery",
  "title": "Rail Demurrage & Accessorial Recovery",
  "shortTitle": "Rail Charge Recovery",
  "tagline": "Reconstruct railcar placement, free time, dwell, switching, storage, and carrier responsibility",
  "industry": "Rail Shipper Financial Operations",
  "uiPort": 4584,
  "apiPort": 5584,
  "accent": "#92400e",
  "currency": "USD",
  "primaryOutcome": "Incorrect rail demurrage and accessorial charges disputed, credited, and prevented before recurrence",
  "valueNarrative": "Unify rail tariffs, waybills, railcar events, placement, interchange, plant capacity, closures, invoices, and carrier responses.",
  "calculation": {
    "actualKey": "billedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Railroad Billed Amount",
    "expectedLabel": "Tariff-Supported Amount",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Railcar events, placement rules, tariff free time, and carrier responsibility indicate recoverable rail charges.",
    "actions": [
      "Validate the governing agreement and effective rules",
      "Reconcile transaction-level source evidence",
      "Prepare and submit the recovery or correction package",
      "Track response and reconcile realized financial outcome"
    ]
  }
},[
feature("rail-tariff-and-contract-library","RCR01","Rail tariff and contract library","Reconcile rail tariff and contract library using rail contracts, tariffs, railcar registries, waybills, interchange events, actual and constructive placement, plant operating records, closures, invoices, and credits.","Produce a governed rail tariff and contract library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["railroadCar","Railroad / Railcar","text","Continental Rail / TBOX-884120"],["caseReference","Rail tariff and contract library Reference","text","RCR01-2026-001"],["billedAmount","Railroad Billed Amount","currency",274000],["supportedAmount","Tariff-Supported Amount","currency",187500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Industrial plant demurrage","Intermodal storage","Private railcar fleet","Unit train facility","Cross-border rail movement"]}),
feature("railcar-and-equipment-registry","RCR02","Railcar and equipment registry","Reconcile railcar and equipment registry using rail contracts, tariffs, railcar registries, waybills, interchange events, actual and constructive placement, plant operating records, closures, invoices, and credits.","Produce a governed railcar and equipment registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["railroadCar","Railroad / Railcar","text","Continental Rail / TBOX-884120"],["caseReference","Railcar and equipment registry Reference","text","RCR02-2026-001"],["billedAmount","Railroad Billed Amount","currency",274000],["supportedAmount","Tariff-Supported Amount","currency",187500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Industrial plant demurrage","Intermodal storage","Private railcar fleet","Unit train facility","Cross-border rail movement"]}),
feature("waybill-ingestion","RCR03","Waybill ingestion","Reconcile waybill ingestion using rail contracts, tariffs, railcar registries, waybills, interchange events, actual and constructive placement, plant operating records, closures, invoices, and credits.","Produce a governed waybill ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["railroadCar","Railroad / Railcar","text","Continental Rail / TBOX-884120"],["caseReference","Waybill ingestion Reference","text","RCR03-2026-001"],["billedAmount","Railroad Billed Amount","currency",274000],["supportedAmount","Tariff-Supported Amount","currency",187500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Industrial plant demurrage","Intermodal storage","Private railcar fleet","Unit train facility","Cross-border rail movement"]}),
feature("event-and-interchange-timeline","RCR04","Event and interchange timeline","Reconcile event and interchange timeline using rail contracts, tariffs, railcar registries, waybills, interchange events, actual and constructive placement, plant operating records, closures, invoices, and credits.","Produce a governed event and interchange timeline decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["railroadCar","Railroad / Railcar","text","Continental Rail / TBOX-884120"],["caseReference","Event and interchange timeline Reference","text","RCR04-2026-001"],["billedAmount","Railroad Billed Amount","currency",274000],["supportedAmount","Tariff-Supported Amount","currency",187500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Industrial plant demurrage","Intermodal storage","Private railcar fleet","Unit train facility","Cross-border rail movement"]}),
feature("actual-placement-calculation","RCR05","Actual placement calculation","Reconcile actual placement calculation using rail contracts, tariffs, railcar registries, waybills, interchange events, actual and constructive placement, plant operating records, closures, invoices, and credits.","Produce a governed actual placement calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["railroadCar","Railroad / Railcar","text","Continental Rail / TBOX-884120"],["caseReference","Actual placement calculation Reference","text","RCR05-2026-001"],["billedAmount","Railroad Billed Amount","currency",274000],["supportedAmount","Tariff-Supported Amount","currency",187500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Industrial plant demurrage","Intermodal storage","Private railcar fleet","Unit train facility","Cross-border rail movement"]}),
feature("constructive-placement-calculation","RCR06","Constructive placement calculation","Reconcile constructive placement calculation using rail contracts, tariffs, railcar registries, waybills, interchange events, actual and constructive placement, plant operating records, closures, invoices, and credits.","Produce a governed constructive placement calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["railroadCar","Railroad / Railcar","text","Continental Rail / TBOX-884120"],["caseReference","Constructive placement calculation Reference","text","RCR06-2026-001"],["billedAmount","Railroad Billed Amount","currency",274000],["supportedAmount","Tariff-Supported Amount","currency",187500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Industrial plant demurrage","Intermodal storage","Private railcar fleet","Unit train facility","Cross-border rail movement"]}),
feature("free-time-calculation","RCR07","Free-time calculation","Reconcile free-time calculation using rail contracts, tariffs, railcar registries, waybills, interchange events, actual and constructive placement, plant operating records, closures, invoices, and credits.","Produce a governed free-time calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["railroadCar","Railroad / Railcar","text","Continental Rail / TBOX-884120"],["caseReference","Free-time calculation Reference","text","RCR07-2026-001"],["billedAmount","Railroad Billed Amount","currency",274000],["supportedAmount","Tariff-Supported Amount","currency",187500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Industrial plant demurrage","Intermodal storage","Private railcar fleet","Unit train facility","Cross-border rail movement"]}),
feature("demurrage-recalculation","RCR08","Demurrage recalculation","Reconcile demurrage recalculation using rail contracts, tariffs, railcar registries, waybills, interchange events, actual and constructive placement, plant operating records, closures, invoices, and credits.","Produce a governed demurrage recalculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["railroadCar","Railroad / Railcar","text","Continental Rail / TBOX-884120"],["caseReference","Demurrage recalculation Reference","text","RCR08-2026-001"],["billedAmount","Railroad Billed Amount","currency",274000],["supportedAmount","Tariff-Supported Amount","currency",187500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Industrial plant demurrage","Intermodal storage","Private railcar fleet","Unit train facility","Cross-border rail movement"]}),
feature("storage-and-switching-audit","RCR09","Storage and switching audit","Reconcile storage and switching audit using rail contracts, tariffs, railcar registries, waybills, interchange events, actual and constructive placement, plant operating records, closures, invoices, and credits.","Produce a governed storage and switching audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["railroadCar","Railroad / Railcar","text","Continental Rail / TBOX-884120"],["caseReference","Storage and switching audit Reference","text","RCR09-2026-001"],["billedAmount","Railroad Billed Amount","currency",274000],["supportedAmount","Tariff-Supported Amount","currency",187500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Industrial plant demurrage","Intermodal storage","Private railcar fleet","Unit train facility","Cross-border rail movement"]}),
feature("empty-return-rule-validation","RCR10","Empty-return rule validation","Reconcile empty-return rule validation using rail contracts, tariffs, railcar registries, waybills, interchange events, actual and constructive placement, plant operating records, closures, invoices, and credits.","Produce a governed empty-return rule validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["railroadCar","Railroad / Railcar","text","Continental Rail / TBOX-884120"],["caseReference","Empty-return rule validation Reference","text","RCR10-2026-001"],["billedAmount","Railroad Billed Amount","currency",274000],["supportedAmount","Tariff-Supported Amount","currency",187500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Industrial plant demurrage","Intermodal storage","Private railcar fleet","Unit train facility","Cross-border rail movement"]}),
feature("bunching-and-carrier-delay-analysis","RCR11","Bunching and carrier-delay analysis","Reconcile bunching and carrier-delay analysis using rail contracts, tariffs, railcar registries, waybills, interchange events, actual and constructive placement, plant operating records, closures, invoices, and credits.","Produce a governed bunching and carrier-delay analysis decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["railroadCar","Railroad / Railcar","text","Continental Rail / TBOX-884120"],["caseReference","Bunching and carrier-delay analysis Reference","text","RCR11-2026-001"],["billedAmount","Railroad Billed Amount","currency",274000],["supportedAmount","Tariff-Supported Amount","currency",187500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Industrial plant demurrage","Intermodal storage","Private railcar fleet","Unit train facility","Cross-border rail movement"]}),
feature("closure-and-force-majeure-evidence","RCR12","Closure and force-majeure evidence","Reconcile closure and force-majeure evidence using rail contracts, tariffs, railcar registries, waybills, interchange events, actual and constructive placement, plant operating records, closures, invoices, and credits.","Produce a governed closure and force-majeure evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["railroadCar","Railroad / Railcar","text","Continental Rail / TBOX-884120"],["caseReference","Closure and force-majeure evidence Reference","text","RCR12-2026-001"],["billedAmount","Railroad Billed Amount","currency",274000],["supportedAmount","Tariff-Supported Amount","currency",187500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Industrial plant demurrage","Intermodal storage","Private railcar fleet","Unit train facility","Cross-border rail movement"]}),
feature("invoice-validation","RCR13","Invoice validation","Reconcile invoice validation using rail contracts, tariffs, railcar registries, waybills, interchange events, actual and constructive placement, plant operating records, closures, invoices, and credits.","Produce a governed invoice validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["railroadCar","Railroad / Railcar","text","Continental Rail / TBOX-884120"],["caseReference","Invoice validation Reference","text","RCR13-2026-001"],["billedAmount","Railroad Billed Amount","currency",274000],["supportedAmount","Tariff-Supported Amount","currency",187500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Industrial plant demurrage","Intermodal storage","Private railcar fleet","Unit train facility","Cross-border rail movement"]}),
feature("rail-dispute-package","RCR14","Rail dispute package","Reconcile rail dispute package using rail contracts, tariffs, railcar registries, waybills, interchange events, actual and constructive placement, plant operating records, closures, invoices, and credits.","Produce a governed rail dispute package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["railroadCar","Railroad / Railcar","text","Continental Rail / TBOX-884120"],["caseReference","Rail dispute package Reference","text","RCR14-2026-001"],["billedAmount","Railroad Billed Amount","currency",274000],["supportedAmount","Tariff-Supported Amount","currency",187500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Industrial plant demurrage","Intermodal storage","Private railcar fleet","Unit train facility","Cross-border rail movement"]}),
feature("carrier-credit-tracking","RCR15","Carrier credit tracking","Reconcile carrier credit tracking using rail contracts, tariffs, railcar registries, waybills, interchange events, actual and constructive placement, plant operating records, closures, invoices, and credits.","Produce a governed carrier credit tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["railroadCar","Railroad / Railcar","text","Continental Rail / TBOX-884120"],["caseReference","Carrier credit tracking Reference","text","RCR15-2026-001"],["billedAmount","Railroad Billed Amount","currency",274000],["supportedAmount","Tariff-Supported Amount","currency",187500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Industrial plant demurrage","Intermodal storage","Private railcar fleet","Unit train facility","Cross-border rail movement"]}),
feature("dwell-alerts-and-lane-analytics","RCR16","Dwell alerts and lane analytics","Reconcile dwell alerts and lane analytics using rail contracts, tariffs, railcar registries, waybills, interchange events, actual and constructive placement, plant operating records, closures, invoices, and credits.","Produce a governed dwell alerts and lane analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["railroadCar","Railroad / Railcar","text","Continental Rail / TBOX-884120"],["caseReference","Dwell alerts and lane analytics Reference","text","RCR16-2026-001"],["billedAmount","Railroad Billed Amount","currency",274000],["supportedAmount","Tariff-Supported Amount","currency",187500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Industrial plant demurrage","Intermodal storage","Private railcar fleet","Unit train facility","Cross-border rail movement"]})
]);
